version: '2'
services:
  web:
    container_name: dockerflask
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:8000"
    volumes:
      - /home/alex/Documents/fyp/db/:/home/alex/Documents/fyp/db/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`fyp.debateomatic.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=web"
  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

